// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that allows users to provide feedback on AI responses, which is then incorporated into future responses.
 *
 * - incorporateFeedback - A function that handles the feedback incorporation process.
 * - IncorporateFeedbackInput - The input type for the incorporateFeedback function.
 * - IncorporateFeedbackOutput - The return type for the incorporateFeedback function.
 */

import {ai} from '@/ai/genkit';
import {
    IncorporateFeedbackInputSchema,
    type IncorporateFeedbackInput,
    IncorporateFeedbackOutputSchema,
    type IncorporateFeedbackOutput,
} from '@/ai/schemas';

export async function incorporateFeedback(input: IncorporateFeedbackInput): Promise<IncorporateFeedbackOutput> {
  return incorporateFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'incorporateFeedbackPrompt',
  input: {schema: IncorporateFeedbackInputSchema},
  output: {schema: IncorporateFeedbackOutputSchema},
  prompt: `You are an AI assistant that incorporates user feedback to improve future responses.

  The user has provided the following feedback on your previous response to the following prompt.  Use this feedback to improve your response.  You should follow the user's instructions and incorporate their suggestions to produce a better response.

  Original Prompt: {{{originalPrompt}}}
  AI Response: {{{aiResponse}}}
  Feedback: {{{feedback}}}

  Improved Response: `,
});

const incorporateFeedbackFlow = ai.defineFlow(
  {
    name: 'incorporateFeedbackFlow',
    inputSchema: IncorporateFeedbackInputSchema,
    outputSchema: IncorporateFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
