'use client';
import { User, ThumbsUp, ThumbsDown } from 'lucide-react';
import { ScriptIcon } from '@/components/icons';
import { cn } from '@/lib/utils';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import type { Message } from './chat-panel';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface ChatMessageProps {
  message: Message;
  onFeedback: (messageId: string) => void;
}

export function ChatMessage({ message, onFeedback }: ChatMessageProps) {
  const isModel = message.role === 'model';

  return (
    <div className={cn('group flex items-start space-x-4')}>
      <Avatar className="h-8 w-8 border">
        {isModel ? (
          <AvatarFallback className='bg-primary text-primary-foreground'>
            <ScriptIcon className="h-5 w-5" />
          </AvatarFallback>
        ) : (
          <>
            <AvatarImage src="https://placehold.co/40x40.png" alt="User" data-ai-hint="woman portrait" />
            <AvatarFallback>
              <User className="h-5 w-5" />
            </AvatarFallback>
          </>
        )}
      </Avatar>
      
      <div className={cn(
        "max-w-[80%] rounded-lg px-4 py-3",
        isModel ? 'bg-secondary' : 'bg-secondary'
      )}>
        <div className="prose prose-sm dark:prose-invert max-w-none break-words">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {message.content}
          </ReactMarkdown>
        </div>
        {message.imageUrl && (
          <div className="mt-2 rounded-lg overflow-hidden border">
            <img src={message.imageUrl} alt="Generated by AI" className="max-w-sm w-full h-auto" />
          </div>
        )}
      </div>

      {isModel && (
        <div className="opacity-0 group-hover:opacity-100 transition-opacity flex items-center self-center gap-1">
          <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground">
            <ThumbsUp className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={() => onFeedback(message.id)}>
            <ThumbsDown className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  );
}
